# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.6-browsers`
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.2-dependencies-{{ checksum "scripts/environment.yml" }}

      - run:
          name: install dependencies
          command: |
            ENVS=$(conda env list | awk '{print $1}' )
            echo $ENVS
            if ! [[ $ENVS = *"fcfs-monkeys"* ]]; then
              source /opt/conda/etc/profile.d/conda.sh
              conda update -n base -c defaults conda
              conda env create -f scripts/environment.yml
              conda activate fcfs-monkeys
              conda install pytorch torchvision cpuonly -c pytorch
              pip install transformers
            else
              echo "Conda env already installed"
            fi;

      - save_cache:
          key: v1.2-dependencies-{{ checksum "scripts/environment.yml" }}
          paths:
            - /opt/conda

      - run:
          name: run linter
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate fcfs-monkeys
            pylint src/ --rcfile .pylintrc

      - store_artifacts:
          path: test-reports
          destination: test-reports
